language: node_js
node_js:
  - 8.17.0
cache: npm

before_install:
  - npm i -g npm@6.13.4

branches:
  only:
  - master

before_script:
  - pwd
  - cd /home/amira_noaman/travis
  - touch abc

script:
  - npm install

deploy:
  provider: azure_web_apps
  username: amira_noaman       # If AZURE_WA_USERNAME isn't set
  password: passwordamira@1   # If AZURE_WA_PASSWORD isn't set
  site: test-web-eus-vm1    # If AZURE_WA_SITE isn't set
  verbose: true

notifications:
  email:
    recipients:
      - amira.noaman21@gmail.com
    on_success: always # default: change
    on_failure: always # default: always

dist: bionic

