language: node_js
node_js:
- 8.17.0
cache: npm
before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out .travis/deploy_rsa -d
- npm i -g npm@6.13.4
branches:
  only:
  - master
before_script:
- pwd
- curl ifconfig.me
script:
- npm install
deploy:
  provider: azure_web_apps
  username: amira_noaman
  password: passwordamira@1
  site: test-web-eus-vm1
  verbose: true
notifications:
  email:
    recipients:
    - amira.noaman21@gmail.com
    on_success: always
    on_failure: always
dist: bionic
